### PR TITLE
Also filter after callback.

### PR DESCRIPTION
**Pull request by lucasmichot**
Also filter after callback.

### CODE REVIEW

**Comment by usmanhalalit** [comment]
What does it do btw? I think I'm lost 😄

**Comment by lucasmichot** [comment]
It will ensure that the row which are not passing the callback won't be actually integrated; as of: https://github.com/usmanhalalit/laracsv/blob/c845b3b40f29768b2d9491a772504c674672c6bb/src/Laracsv/Export.php#L123-L128

**Comment by usmanhalalit** [comment]
Cool 🙂 
I suck at collections

**Comment by lucasmichot** [comment]
Hé hé, have a look at that: https://adamwathan.me/refactoring-to-collections/

**Comment by usmanhalalit** [comment]
Thanks, came across it but still goes beyond me 🤓

**Pull request merged**
